linux:
	env GOOS=linux GOARCH=amd64 go build demo.go

osx:
	env GOOS=darwin GOARCH=amd64 go build demo.go

win:
	env GOOS=windows GOARCH=amd64 go build demo.go

android:
	env GOOS=android GOARCH=arm go build demo.go

clean:
	go clean

# https://www.digitalocean.com/community/tutorials/how-to-build-go-executables-for-multiple-platforms-on-ubuntu-16-04